name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags:
    - '*'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v3
      with:
        submodules: true
    - run: (cd packages/shim-deno/third_party/deno; git submodule update --init --depth=1 test_util/std)
      shell: bash
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    - uses: denoland/setup-deno@v1
      with:
        deno-version: 1.40.2
    - run: deno lint
      if: matrix.os == 'ubuntu-latest'
    - run: deno fmt --check
      if: matrix.os == 'ubuntu-latest'
    - run: npm -v
    - run: npm ci --ignore-scripts
    - run: npm run --silent build --workspaces
    - run: npm run --silent test --workspaces
    - run: cd packages/shim-deno && tools/untested.sh
      if: matrix.os == 'ubuntu-latest'
