name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags:
    - '*'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: (cd packages/shim-deno/third_party/deno; git submodule update --init --depth=1 test_util/std)
      shell: bash
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'
    - uses: denoland/setup-deno@v1
      with:
        deno-version: ~1.17
    - run: deno lint --config deno.json
      if: matrix.os == 'ubuntu-latest'
    - run: deno fmt --config deno.json --check
      if: matrix.os == 'ubuntu-latest'
    - run: npm ci  --ignore-scripts
    - run: npm run --silent test --workspaces
    - run: npm run --silent prepare --workspaces
    - run: cd packages/shim-deno && tools/missing.ts || echo "Some items are missing"
      if: matrix.os == 'ubuntu-latest'
    - run: cd packages/shim-deno && tools/untested.sh
      if: matrix.os == 'ubuntu-latest'
    - name: npm publish
      if: matrix.os == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/') && github.repository == 'denoland/node_deno_shims'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: cd packages/shim-deno && npm publish
