name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: (cd thirdparty/deno; git submodule update --init --depth=1 test_util/std)
      shell: bash
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: denoland/setup-deno@v1
      with:
        deno-version: ~1.14
    - run: deno lint --ignore=thirdparty/
      if: matrix.os == 'ubuntu-latest'
    - run: deno fmt  --ignore=thirdparty/ --check
      if: matrix.os == 'ubuntu-latest'
    - run: npm ci  --ignore-scripts
    - run: npm run --silent test
    - run: npm run --silent denolib
    - run: tools/missing.ts || echo "Some items are missing"
    - run: tools/untested.sh
