name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: (cd thirdparty/deno; git submodule update --init test_util/std --depth=1)
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: denoland/setup-deno@v1
      with:
        deno-version: ~1.13
    - run: deno lint --ignore=thirdparty/
    - run: deno fmt  --ignore=thirdparty/ --check
    - run: npm ci  --ignore-scripts
    - run: npm run --silent test
    - run: npm run --silent denolib
    - run: tools/missing.ts
    - run: tools/untested.sh
